In [1]:
import os
import h5py
from PIL import Image
import numpy as np

import struct
import matplotlib.pyplot as plt
import torch
import torchvision.transforms as transforms

In [2]:
NX = 276
NZ = 276

In [3]:
workpath = "./"
phase = 'train' #['train', 'test']
mode = 'B' #['A', 'B']
content = ['vx_split', 'vz_split']

fileNum = 0 
for root,dirs,files in os.walk(workpath + content[0]):    #遍历统计  
    for each in files:  
        if each[-4:] == '.png':  
            #print( root,dirs,each)  
            fileNum += 1  
#print(fileNum)

outfile = h5py.File(workpath + phase + mode +'.h5', 'w')  #./trainB.h5
outdata = torch.zeros((2, NX, NZ))

for count in range(1, fileNum):
    for i, iterm in enumerate(content):
        iname = workpath + iterm + "/" + mode + str(count) + ".png" # ./vz_split/B1.png
        data = Image.open(iname).convert('L').resize((NX, NZ)) # 276*276
        outdata[i] = transforms.ToTensor()(data) #np.matrix(data, dtype='float')/255.0
    #infile = Image.open(iname)
    outfile.create_dataset(mode+str(count), data=outdata, dtype=np.float64) #B1.png
outfile.close()

In [4]:
workpath = "./"
phase = 'train' #['train', 'test']
mode = 'A' #['A', 'B']
content = ['curl_split', 'div_split']

fileNum = 0 
for root,dirs,files in os.walk(workpath + content[0]):    #遍历统计  
    for each in files:  
        if each[-4:] == '.png':  
            #print( root,dirs,each)  
            fileNum += 1  
#print(fileNum)

outfile = h5py.File(workpath + phase + mode +'.h5', 'w')  #./trainB.h5
outdata = torch.zeros((2, NX, NZ))

for count in range(1, fileNum):
    for i, iterm in enumerate(content):
        iname = workpath + iterm + "/" + mode + str(count) + ".png" # ./vz_split/B1.png
        data = Image.open(iname).convert('L').resize((NX, NZ)) # 276*276
        outdata[i] = transforms.ToTensor()(data) #np.matrix(data, dtype='float')/255.0
    #infile = Image.open(iname)
    outfile.create_dataset(mode+str(count), data=outdata, dtype=np.float64) #B1.png
outfile.close()

In [5]:
%hist -f makeHDF5.py

In [7]:
testfile = h5py.File(workpath + phase + mode+'.h5', 'r')
pic1 = testfile['A1']
#testfile.close()


In [8]:
pic1

<HDF5 dataset "A1": shape (2, 276, 276), type "<f8">

In [11]:
import torch
test=torch.Tensor(pic1)

In [12]:
test


  127   127   128  ...    128   127   127
  127   127   128  ...    128   127   127
  127   127   128  ...    128   127   127
       ...          ⋱          ...       
  127   128   128  ...    128   127   127
  127   128   128  ...    128   127   127
  127   128   128  ...    128   127   127
[torch.FloatTensor of size 276x276]

In [30]:
aa = Image.open('./vz_split/B1.png')
data = aa.convert('L').resize((276, 276))#, Image.BICUBIC)#.getdata()
#data = np.matrix(data, dtype='float')/255.0
#sub_ts = torch.from_numpy(sub_img)  
import torchvision.transforms as transforms
A = transforms.ToTensor()(data)
B = transforms.ToTensor()(data)
C = torch.zeros((2, 276, 276))
C[0]  = A
C[1] = B
#import torch
#test = torch.Tensor(data)

In [31]:
C

tensor([[[0.4471, 0.4471, 0.4471,  ..., 0.4510, 0.4510, 0.4510],
         [0.4235, 0.4314, 0.4275,  ..., 0.4235, 0.4235, 0.4235],
         [0.4157, 0.2588, 0.3922,  ..., 0.4314, 0.4314, 0.4314],
         ...,
         [0.3373, 0.4706, 0.5294,  ..., 0.4353, 0.4353, 0.4353],
         [0.5255, 0.5059, 0.4196,  ..., 0.4314, 0.4314, 0.4314],
         [0.4588, 0.3804, 0.3765,  ..., 0.4275, 0.4314, 0.4314]],

        [[0.4471, 0.4471, 0.4471,  ..., 0.4510, 0.4510, 0.4510],
         [0.4235, 0.4314, 0.4275,  ..., 0.4235, 0.4235, 0.4235],
         [0.4157, 0.2588, 0.3922,  ..., 0.4314, 0.4314, 0.4314],
         ...,
         [0.3373, 0.4706, 0.5294,  ..., 0.4353, 0.4353, 0.4353],
         [0.5255, 0.5059, 0.4196,  ..., 0.4314, 0.4314, 0.4314],
         [0.4588, 0.3804, 0.3765,  ..., 0.4275, 0.4314, 0.4314]]])

In [29]:
help(torch.cat)

Help on built-in function cat:

cat(...)
    cat(seq, dim=0, out=None) -> Tensor
    
    Concatenates the given sequence of :attr:`seq` tensors in the given dimension.
    All tensors must either have the same shape (except in the concatenating
    dimension) or be empty.
    
    :func:`torch.cat` can be seen as an inverse operation for :func:`torch.split`
    and :func:`torch.chunk`.
    
    :func:`torch.cat` can be best understood via examples.
    
    Args:
        seq (sequence of Tensors): any python sequence of tensors of the same type.
            Non-empty tensors provided must have the same shape, except in the
            cat dimension.
        dim (int, optional): the dimension over which the tensors are concatenated
        out (Tensor, optional): the output tensor
    
    Example::
    
        >>> x = torch.randn(2, 3)
        >>> x
        tensor([[ 0.6580, -1.0969, -0.4614],
                [-0.1034, -0.5790,  0.1497]])
        >>> torch.cat((x, x, x), 0)
        t

In [9]:
content = ['vx_split', 'vz_split']
for i, iterm in enumerate(content):
    print(i, iterm)

0 vx_split
1 vz_split


In [13]:
outdata = np.empty((2, 3, 1))

In [15]:
outdata[0] = [[0], [0], [0]]
outdata[1] = [[1], [1], [1]]

In [12]:
outdata

array([[[0.]],

       [[1.]]])

In [20]:
workpath + content[0]

'./vx_split'